name: Run Data Integrity Tests

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to main
  pull_request:
    branches:
      - main  # Runs tests on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.3.4 exceptiongroup==1.2.2 iniconfig==2.0.0 packaging==24.2

      - name: Run Pytest for Data Integrity
        run: pytest tests/data_integrity_pytest.py